/**
 * Mnemonist Library Endpoint (CommonJS)
 * ======================================
 *
 * Exporting every data structure through a unified endpoint. Consumers
 * of this library should prefer the modular access though.
 */
module.exports = {
  BiMap: require('./bi-map.js'),
  BitSet: require('./bit-set.js'),
  BitVector: require('./bit-vector.js'),
  BloomFilter: require('./bloom-filter.js'),
  BKTree: require('./bk-tree.js'),
  CircularBuffer: require('./circular-buffer.js'),
  DefaultMap: require('./default-map.js'),
  DefaultWeakMap: require('./default-weak-map.js'),
  FixedDeque: require('./fixed-deque.js'),
  StaticDisjointSet: require('./static-disjoint-set.js'),
  FibonacciHeap: require('./fibonacci-heap.js'),
  MinFibonacciHeap: require('./fibonacci-heap.js').MinFibonacciHeap,
  MaxFibonacciHeap: require('./fibonacci-heap.js').MaxFibonacciHeap,
  FixedReverseHeap: require('./fixed-reverse-heap.js'),
  FuzzyMap: require('./fuzzy-map.js'),
  FuzzyMultiMap: require('./fuzzy-multi-map.js'),
  HashedArrayTree: require('./hashed-array-tree.js'),
  Heap: require('./heap.js'),
  MinHeap: require('./heap.js').MinHeap,
  MaxHeap: require('./heap.js').MaxHeap,
  StaticIntervalTree: require('./static-interval-tree.js'),
  InvertedIndex: require('./inverted-index.js'),
  KDTree: require('./kd-tree.js'),
  LinkedList: require('./linked-list.js'),
  LRUCache: require('./lru-cache.js'),
  LRUCacheWithDelete: require('./lru-cache-with-delete.js'),
  LRUMap: require('./lru-map.js'),
  LRUMapWithDelete: require('./lru-map-with-delete.js'),
  MultiMap: require('./multi-map.js'),
  MultiSet: require('./multi-set.js'),
  PassjoinIndex: require('./passjoin-index.js'),
  Queue: require('./queue.js'),
  FixedStack: require('./fixed-stack.js'),
  Stack: require('./stack.js'),
  SuffixArray: require('./suffix-array.js'),
  GeneralizedSuffixArray: require('./suffix-array.js').GeneralizedSuffixArray,
  set: require('./set.js'),
  SparseQueueSet: require('./sparse-queue-set.js'),
  SparseMap: require('./sparse-map.js'),
  SparseSet: require('./sparse-set.js'),
  SymSpell: require('./symspell.js'),
  Trie: require('./trie.js'),
  TrieMap: require('./trie-map.js'),
  Vector: require('./vector.js'),
  Uint8Vector: require('./vector.js').Uint8Vector,
  Uint8ClampedVector: require('./vector.js').Uint8ClampedVector,
  Int8Vector: require('./vector.js').Int8Vector,
  Uint16Vector: require('./vector.js').Uint16Vector,
  Int16Vector: require('./vector.js').Int16Vector,
  Uint32Vector: require('./vector.js').Uint32Vector,
  Int32Vector: require('./vector.js').Int32Vector,
  Float32Vector: require('./vector.js').Float32Vector,
  Float64Vector: require('./vector.js').Float64Vector,
  PointerVector: require('./vector.js').PointerVector,
  VPTree: require('./vp-tree.js')
};
