name: Tests

on: [push, pull_request]

jobs:

  tests:
    strategy:
      matrix:
        # npm will not run under 10.x or earlier and so they cannot be tested
        node-version:
            - 12.x
            - 14.x
            - 16.x
            - 18.x
            - 20.x
            - latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Lint & Test
        run: |
          npm i
          npm run lint
          npm test
          # Typescript does not work with node 12.x
          [[ "${{ matrix.node-version }}" != "12.x" ]] && npm run test:exports || true
