name: Tests

on: [push, pull_request]

jobs:

  tests:
    strategy:
      matrix:
        # npm will not run under 10.x or earlier and so they cannot be tested
        node-version:
            - 12.x
            - 13.x
            - 14.x
            - 15.x
            - 16.x
            - 18.x
            - latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Lint & Test
        run: |
          npm i -g npm
          npm i
          npm run lint
          npm test
          npm run test:types
